kind: pipeline
name: default

steps:
  - name: install
    image: node:8
    commands:
      - npm install
  - name: test
    image: node:8
    commands:
      - npm run lint
      - npm test
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
      files:
        - coverage/coverage-final.json
  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: NPM_USERNAME
      password:
        from_secret: NPM_PASSWORD
      email: joeyjiron06@gmail.com
    when:
      branch:
        - master
